
CREATE TABLE IF NOT EXISTS users (
 id UUID PRIMARY KEY,
 name TEXT,
 email TEXT,
 image TEXT
);

CREATE TABLE IF NOT EXISTS boards (
 id UUID PRIMARY KEY,
 user_id UUID,
 data JSONB,
 updated_at TIMESTAMP DEFAULT NOW()
);